// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aws/aws-sdk-go-v2/service/sfn/sfniface (interfaces: ClientAPI)

// Package mock is a generated GoMock package.
package mock

import (
	"reflect"

	"github.com/aws/aws-sdk-go-v2/service/sfn"
	"github.com/golang/mock/gomock"
)

// MockClientAPI is a mock of ClientAPI interface
type MockClientAPI struct {
	ctrl     *gomock.Controller
	recorder *MockClientAPIMockRecorder
}

// MockClientAPIMockRecorder is the mock recorder for MockClientAPI
type MockClientAPIMockRecorder struct {
	mock *MockClientAPI
}

// NewMockClientAPI creates a new mock instance
func NewMockClientAPI(ctrl *gomock.Controller) *MockClientAPI {
	mock := &MockClientAPI{ctrl: ctrl}
	mock.recorder = &MockClientAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockClientAPI) EXPECT() *MockClientAPIMockRecorder {
	return m.recorder
}

// CreateActivityRequest mocks base method
func (m *MockClientAPI) CreateActivityRequest(arg0 *sfn.CreateActivityInput) sfn.CreateActivityRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateActivityRequest", arg0)
	ret0, _ := ret[0].(sfn.CreateActivityRequest)
	return ret0
}

// CreateActivityRequest indicates an expected call of CreateActivityRequest
func (mr *MockClientAPIMockRecorder) CreateActivityRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateActivityRequest", reflect.TypeOf((*MockClientAPI)(nil).CreateActivityRequest), arg0)
}

// CreateStateMachineRequest mocks base method
func (m *MockClientAPI) CreateStateMachineRequest(arg0 *sfn.CreateStateMachineInput) sfn.CreateStateMachineRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStateMachineRequest", arg0)
	ret0, _ := ret[0].(sfn.CreateStateMachineRequest)
	return ret0
}

// CreateStateMachineRequest indicates an expected call of CreateStateMachineRequest
func (mr *MockClientAPIMockRecorder) CreateStateMachineRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStateMachineRequest", reflect.TypeOf((*MockClientAPI)(nil).CreateStateMachineRequest), arg0)
}

// DeleteActivityRequest mocks base method
func (m *MockClientAPI) DeleteActivityRequest(arg0 *sfn.DeleteActivityInput) sfn.DeleteActivityRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteActivityRequest", arg0)
	ret0, _ := ret[0].(sfn.DeleteActivityRequest)
	return ret0
}

// DeleteActivityRequest indicates an expected call of DeleteActivityRequest
func (mr *MockClientAPIMockRecorder) DeleteActivityRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteActivityRequest", reflect.TypeOf((*MockClientAPI)(nil).DeleteActivityRequest), arg0)
}

// DeleteStateMachineRequest mocks base method
func (m *MockClientAPI) DeleteStateMachineRequest(arg0 *sfn.DeleteStateMachineInput) sfn.DeleteStateMachineRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteStateMachineRequest", arg0)
	ret0, _ := ret[0].(sfn.DeleteStateMachineRequest)
	return ret0
}

// DeleteStateMachineRequest indicates an expected call of DeleteStateMachineRequest
func (mr *MockClientAPIMockRecorder) DeleteStateMachineRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteStateMachineRequest", reflect.TypeOf((*MockClientAPI)(nil).DeleteStateMachineRequest), arg0)
}

// DescribeActivityRequest mocks base method
func (m *MockClientAPI) DescribeActivityRequest(arg0 *sfn.DescribeActivityInput) sfn.DescribeActivityRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeActivityRequest", arg0)
	ret0, _ := ret[0].(sfn.DescribeActivityRequest)
	return ret0
}

// DescribeActivityRequest indicates an expected call of DescribeActivityRequest
func (mr *MockClientAPIMockRecorder) DescribeActivityRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeActivityRequest", reflect.TypeOf((*MockClientAPI)(nil).DescribeActivityRequest), arg0)
}

// DescribeExecutionRequest mocks base method
func (m *MockClientAPI) DescribeExecutionRequest(arg0 *sfn.DescribeExecutionInput) sfn.DescribeExecutionRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeExecutionRequest", arg0)
	ret0, _ := ret[0].(sfn.DescribeExecutionRequest)
	return ret0
}

// DescribeExecutionRequest indicates an expected call of DescribeExecutionRequest
func (mr *MockClientAPIMockRecorder) DescribeExecutionRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeExecutionRequest", reflect.TypeOf((*MockClientAPI)(nil).DescribeExecutionRequest), arg0)
}

// DescribeStateMachineForExecutionRequest mocks base method
func (m *MockClientAPI) DescribeStateMachineForExecutionRequest(arg0 *sfn.DescribeStateMachineForExecutionInput) sfn.DescribeStateMachineForExecutionRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeStateMachineForExecutionRequest", arg0)
	ret0, _ := ret[0].(sfn.DescribeStateMachineForExecutionRequest)
	return ret0
}

// DescribeStateMachineForExecutionRequest indicates an expected call of DescribeStateMachineForExecutionRequest
func (mr *MockClientAPIMockRecorder) DescribeStateMachineForExecutionRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeStateMachineForExecutionRequest", reflect.TypeOf((*MockClientAPI)(nil).DescribeStateMachineForExecutionRequest), arg0)
}

// DescribeStateMachineRequest mocks base method
func (m *MockClientAPI) DescribeStateMachineRequest(arg0 *sfn.DescribeStateMachineInput) sfn.DescribeStateMachineRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DescribeStateMachineRequest", arg0)
	ret0, _ := ret[0].(sfn.DescribeStateMachineRequest)
	return ret0
}

// DescribeStateMachineRequest indicates an expected call of DescribeStateMachineRequest
func (mr *MockClientAPIMockRecorder) DescribeStateMachineRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DescribeStateMachineRequest", reflect.TypeOf((*MockClientAPI)(nil).DescribeStateMachineRequest), arg0)
}

// GetActivityTaskRequest mocks base method
func (m *MockClientAPI) GetActivityTaskRequest(arg0 *sfn.GetActivityTaskInput) sfn.GetActivityTaskRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActivityTaskRequest", arg0)
	ret0, _ := ret[0].(sfn.GetActivityTaskRequest)
	return ret0
}

// GetActivityTaskRequest indicates an expected call of GetActivityTaskRequest
func (mr *MockClientAPIMockRecorder) GetActivityTaskRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActivityTaskRequest", reflect.TypeOf((*MockClientAPI)(nil).GetActivityTaskRequest), arg0)
}

// GetExecutionHistoryRequest mocks base method
func (m *MockClientAPI) GetExecutionHistoryRequest(arg0 *sfn.GetExecutionHistoryInput) sfn.GetExecutionHistoryRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExecutionHistoryRequest", arg0)
	ret0, _ := ret[0].(sfn.GetExecutionHistoryRequest)
	return ret0
}

// GetExecutionHistoryRequest indicates an expected call of GetExecutionHistoryRequest
func (mr *MockClientAPIMockRecorder) GetExecutionHistoryRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExecutionHistoryRequest", reflect.TypeOf((*MockClientAPI)(nil).GetExecutionHistoryRequest), arg0)
}

// ListActivitiesRequest mocks base method
func (m *MockClientAPI) ListActivitiesRequest(arg0 *sfn.ListActivitiesInput) sfn.ListActivitiesRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActivitiesRequest", arg0)
	ret0, _ := ret[0].(sfn.ListActivitiesRequest)
	return ret0
}

// ListActivitiesRequest indicates an expected call of ListActivitiesRequest
func (mr *MockClientAPIMockRecorder) ListActivitiesRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActivitiesRequest", reflect.TypeOf((*MockClientAPI)(nil).ListActivitiesRequest), arg0)
}

// ListExecutionsRequest mocks base method
func (m *MockClientAPI) ListExecutionsRequest(arg0 *sfn.ListExecutionsInput) sfn.ListExecutionsRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListExecutionsRequest", arg0)
	ret0, _ := ret[0].(sfn.ListExecutionsRequest)
	return ret0
}

// ListExecutionsRequest indicates an expected call of ListExecutionsRequest
func (mr *MockClientAPIMockRecorder) ListExecutionsRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListExecutionsRequest", reflect.TypeOf((*MockClientAPI)(nil).ListExecutionsRequest), arg0)
}

// ListStateMachinesRequest mocks base method
func (m *MockClientAPI) ListStateMachinesRequest(arg0 *sfn.ListStateMachinesInput) sfn.ListStateMachinesRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListStateMachinesRequest", arg0)
	ret0, _ := ret[0].(sfn.ListStateMachinesRequest)
	return ret0
}

// ListStateMachinesRequest indicates an expected call of ListStateMachinesRequest
func (mr *MockClientAPIMockRecorder) ListStateMachinesRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListStateMachinesRequest", reflect.TypeOf((*MockClientAPI)(nil).ListStateMachinesRequest), arg0)
}

// ListTagsForResourceRequest mocks base method
func (m *MockClientAPI) ListTagsForResourceRequest(arg0 *sfn.ListTagsForResourceInput) sfn.ListTagsForResourceRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTagsForResourceRequest", arg0)
	ret0, _ := ret[0].(sfn.ListTagsForResourceRequest)
	return ret0
}

// ListTagsForResourceRequest indicates an expected call of ListTagsForResourceRequest
func (mr *MockClientAPIMockRecorder) ListTagsForResourceRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTagsForResourceRequest", reflect.TypeOf((*MockClientAPI)(nil).ListTagsForResourceRequest), arg0)
}

// SendTaskFailureRequest mocks base method
func (m *MockClientAPI) SendTaskFailureRequest(arg0 *sfn.SendTaskFailureInput) sfn.SendTaskFailureRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendTaskFailureRequest", arg0)
	ret0, _ := ret[0].(sfn.SendTaskFailureRequest)
	return ret0
}

// SendTaskFailureRequest indicates an expected call of SendTaskFailureRequest
func (mr *MockClientAPIMockRecorder) SendTaskFailureRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendTaskFailureRequest", reflect.TypeOf((*MockClientAPI)(nil).SendTaskFailureRequest), arg0)
}

// SendTaskHeartbeatRequest mocks base method
func (m *MockClientAPI) SendTaskHeartbeatRequest(arg0 *sfn.SendTaskHeartbeatInput) sfn.SendTaskHeartbeatRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendTaskHeartbeatRequest", arg0)
	ret0, _ := ret[0].(sfn.SendTaskHeartbeatRequest)
	return ret0
}

// SendTaskHeartbeatRequest indicates an expected call of SendTaskHeartbeatRequest
func (mr *MockClientAPIMockRecorder) SendTaskHeartbeatRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendTaskHeartbeatRequest", reflect.TypeOf((*MockClientAPI)(nil).SendTaskHeartbeatRequest), arg0)
}

// SendTaskSuccessRequest mocks base method
func (m *MockClientAPI) SendTaskSuccessRequest(arg0 *sfn.SendTaskSuccessInput) sfn.SendTaskSuccessRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendTaskSuccessRequest", arg0)
	ret0, _ := ret[0].(sfn.SendTaskSuccessRequest)
	return ret0
}

// SendTaskSuccessRequest indicates an expected call of SendTaskSuccessRequest
func (mr *MockClientAPIMockRecorder) SendTaskSuccessRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendTaskSuccessRequest", reflect.TypeOf((*MockClientAPI)(nil).SendTaskSuccessRequest), arg0)
}

// StartExecutionRequest mocks base method
func (m *MockClientAPI) StartExecutionRequest(arg0 *sfn.StartExecutionInput) sfn.StartExecutionRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartExecutionRequest", arg0)
	ret0, _ := ret[0].(sfn.StartExecutionRequest)
	return ret0
}

// StartExecutionRequest indicates an expected call of StartExecutionRequest
func (mr *MockClientAPIMockRecorder) StartExecutionRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartExecutionRequest", reflect.TypeOf((*MockClientAPI)(nil).StartExecutionRequest), arg0)
}

// StopExecutionRequest mocks base method
func (m *MockClientAPI) StopExecutionRequest(arg0 *sfn.StopExecutionInput) sfn.StopExecutionRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopExecutionRequest", arg0)
	ret0, _ := ret[0].(sfn.StopExecutionRequest)
	return ret0
}

// StopExecutionRequest indicates an expected call of StopExecutionRequest
func (mr *MockClientAPIMockRecorder) StopExecutionRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopExecutionRequest", reflect.TypeOf((*MockClientAPI)(nil).StopExecutionRequest), arg0)
}

// TagResourceRequest mocks base method
func (m *MockClientAPI) TagResourceRequest(arg0 *sfn.TagResourceInput) sfn.TagResourceRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TagResourceRequest", arg0)
	ret0, _ := ret[0].(sfn.TagResourceRequest)
	return ret0
}

// TagResourceRequest indicates an expected call of TagResourceRequest
func (mr *MockClientAPIMockRecorder) TagResourceRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TagResourceRequest", reflect.TypeOf((*MockClientAPI)(nil).TagResourceRequest), arg0)
}

// UntagResourceRequest mocks base method
func (m *MockClientAPI) UntagResourceRequest(arg0 *sfn.UntagResourceInput) sfn.UntagResourceRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UntagResourceRequest", arg0)
	ret0, _ := ret[0].(sfn.UntagResourceRequest)
	return ret0
}

// UntagResourceRequest indicates an expected call of UntagResourceRequest
func (mr *MockClientAPIMockRecorder) UntagResourceRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UntagResourceRequest", reflect.TypeOf((*MockClientAPI)(nil).UntagResourceRequest), arg0)
}

// UpdateStateMachineRequest mocks base method
func (m *MockClientAPI) UpdateStateMachineRequest(arg0 *sfn.UpdateStateMachineInput) sfn.UpdateStateMachineRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStateMachineRequest", arg0)
	ret0, _ := ret[0].(sfn.UpdateStateMachineRequest)
	return ret0
}

// UpdateStateMachineRequest indicates an expected call of UpdateStateMachineRequest
func (mr *MockClientAPIMockRecorder) UpdateStateMachineRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStateMachineRequest", reflect.TypeOf((*MockClientAPI)(nil).UpdateStateMachineRequest), arg0)
}
