// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aws/aws-sdk-go-v2/service/apigatewaymanagementapi/apigatewaymanagementapiiface (interfaces: ClientAPI)

// Package mock is a generated GoMock package.
package mock

import (
	apigatewaymanagementapi "github.com/aws/aws-sdk-go-v2/service/apigatewaymanagementapi"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockClientAPI is a mock of ClientAPI interface
type MockClientAPI struct {
	ctrl     *gomock.Controller
	recorder *MockClientAPIMockRecorder
}

// MockClientAPIMockRecorder is the mock recorder for MockClientAPI
type MockClientAPIMockRecorder struct {
	mock *MockClientAPI
}

// NewMockClientAPI creates a new mock instance
func NewMockClientAPI(ctrl *gomock.Controller) *MockClientAPI {
	mock := &MockClientAPI{ctrl: ctrl}
	mock.recorder = &MockClientAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockClientAPI) EXPECT() *MockClientAPIMockRecorder {
	return m.recorder
}

// DeleteConnectionRequest mocks base method
func (m *MockClientAPI) DeleteConnectionRequest(arg0 *apigatewaymanagementapi.DeleteConnectionInput) apigatewaymanagementapi.DeleteConnectionRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteConnectionRequest", arg0)
	ret0, _ := ret[0].(apigatewaymanagementapi.DeleteConnectionRequest)
	return ret0
}

// DeleteConnectionRequest indicates an expected call of DeleteConnectionRequest
func (mr *MockClientAPIMockRecorder) DeleteConnectionRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteConnectionRequest", reflect.TypeOf((*MockClientAPI)(nil).DeleteConnectionRequest), arg0)
}

// GetConnectionRequest mocks base method
func (m *MockClientAPI) GetConnectionRequest(arg0 *apigatewaymanagementapi.GetConnectionInput) apigatewaymanagementapi.GetConnectionRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConnectionRequest", arg0)
	ret0, _ := ret[0].(apigatewaymanagementapi.GetConnectionRequest)
	return ret0
}

// GetConnectionRequest indicates an expected call of GetConnectionRequest
func (mr *MockClientAPIMockRecorder) GetConnectionRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConnectionRequest", reflect.TypeOf((*MockClientAPI)(nil).GetConnectionRequest), arg0)
}

// PostToConnectionRequest mocks base method
func (m *MockClientAPI) PostToConnectionRequest(arg0 *apigatewaymanagementapi.PostToConnectionInput) apigatewaymanagementapi.PostToConnectionRequest {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostToConnectionRequest", arg0)
	ret0, _ := ret[0].(apigatewaymanagementapi.PostToConnectionRequest)
	return ret0
}

// PostToConnectionRequest indicates an expected call of PostToConnectionRequest
func (mr *MockClientAPIMockRecorder) PostToConnectionRequest(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostToConnectionRequest", reflect.TypeOf((*MockClientAPI)(nil).PostToConnectionRequest), arg0)
}
